packages:
  - ./extension
  - ./playwright
  - ./tabwright
  - ./website
  - playwright/packages/playwright-core

preferWorkspacePackages: true

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - sharp

ignoredBuiltDependencies:
  - electron
